---
include:
  - board: cornix_left
    artifact-name: cornix_left_seoto

  - board: cornix_right
    artifact-name: cornix_right_seoto

  - board: cornix_left
    shield: settings_reset
    artifact-name: cornix_left_settings_reset

  - board: cornix_right
    shield: settings_reset
    artifact-name: cornix_right_settings_reset
